//! The one generated-types source (G-ACCESS §1.5): pure renderers for
//! `src/lib/access/caps.gen.ts` (from [`super::caps`]) and
//! `src/lib/access/rpc-requirements.gen.ts` (from
//! [`super::rpc_requirements`]), plus a golden test per file (A-2).
//!
//! A golden test fails when the checked-in file differs from the render,
//! and its failure message carries the **full expected file**, so a WP that
//! can't build locally (DEC-50) can copy CI's output into its PR. Run with
//! `IKENGA_UPDATE_GENERATED=1` to rewrite the files instead.

use std::fmt::Write as _;

use super::caps::{
    ArmClass, Cap, ACCESS_SCHEMA_VERSION, ARM_CLASSES, CAPS, NEVER_GRANTABLE, ROLES,
    ROLE_DEFAULT_CAPS, TIERS, TIER_CAPS,
};
use super::rpc_requirements::RPC_REQUIREMENTS;

const HEADER: &str =
    "// GENERATED by src-tauri/src/access/caps_ts.rs — do not edit (G-ACCESS §1.5)\n";

fn quoted<'a>(items: impl IntoIterator<Item = &'a str>) -> String {
    items
        .into_iter()
        .map(|s| format!("'{s}'"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn caps_list(caps: &[Cap]) -> String {
    format!("[{}]", quoted(caps.iter().map(|c| c.as_str())))
}

/// Biome's line width (`biome.json`: 100, tabs counted as 2), so the
/// generated files stay `biome format`-clean.
const WIDTH: usize = 100;

fn width(line: &str) -> usize {
    line.chars().map(|c| if c == '\t' { 2 } else { 1 }).sum()
}

/// `export const NAME = [a, b, …] as const;` on one line if it fits, else
/// one item per line (what `biome format` produces).
fn const_array(name: &str, items: &[&str]) -> String {
    let one = format!(
        "export const {name} = [{}] as const;\n",
        quoted(items.iter().copied())
    );
    if width(one.trim_end()) <= WIDTH {
        return one;
    }
    let mut s = format!("export const {name} = [\n");
    for i in items {
        let _ = writeln!(s, "\t'{i}',");
    }
    s.push_str("] as const;\n");
    s
}

/// `\tkey: { a: 'x', b: 'y' },` on one line if it fits, else expanded.
fn label_entry(key: &str, fields: [(&str, &str); 2]) -> String {
    let one = format!(
        "\t{key}: {{ {}: {}, {}: {} }},\n",
        fields[0].0,
        ts_str(fields[0].1),
        fields[1].0,
        ts_str(fields[1].1)
    );
    if width(one.trim_end()) <= WIDTH {
        return one;
    }
    let mut s = format!("\t{key}: {{\n");
    for (k, v) in fields {
        let _ = writeln!(s, "\t\t{k}: {},", ts_str(v));
    }
    s.push_str("\t},\n");
    s
}

/// A TS single-quoted string literal.
fn ts_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        match ch {
            '\'' => out.push_str("\\'"),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            c => out.push(c),
        }
    }
    out.push('\'');
    out
}

/// `src/lib/access/caps.gen.ts` (exports exactly what §1.5 lists).
pub fn render_caps_ts() -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    s.push('\n');
    let _ = writeln!(
        s,
        "export const ACCESS_SCHEMA_VERSION = {ACCESS_SCHEMA_VERSION} as const;"
    );
    s.push_str(&const_array(
        "CAPS",
        &CAPS.iter().map(|c| c.as_str()).collect::<Vec<_>>(),
    ));
    s.push_str("export type Cap = (typeof CAPS)[number];\n");
    s.push_str(&const_array(
        "TIERS",
        &TIERS.iter().map(|t| t.as_str()).collect::<Vec<_>>(),
    ));
    s.push_str("export type Tier = (typeof TIERS)[number];\n");
    s.push_str("export const TIER_CAPS: Readonly<Record<Tier, readonly Cap[]>> = {\n");
    for (tier, caps) in TIER_CAPS {
        let _ = writeln!(s, "\t{}: {},", tier.as_str(), caps_list(caps));
    }
    s.push_str("};\n");
    s.push_str(&const_array(
        "ROLES",
        &ROLES.iter().map(|r| r.as_str()).collect::<Vec<_>>(),
    ));
    s.push_str("export type Role = (typeof ROLES)[number];\n");
    s.push_str("export const ROLE_DEFAULT_CAPS: Readonly<Record<Role, readonly Cap[]>> = {\n");
    for (role, caps) in ROLE_DEFAULT_CAPS {
        let _ = writeln!(s, "\t{}: {},", role.as_str(), caps_list(caps));
    }
    s.push_str("};\n");
    s.push_str(
        "export const NEVER_GRANTABLE: Readonly<Record<Exclude<Role, 'owner'>, readonly Cap[]>> = {\n",
    );
    for (role, caps) in NEVER_GRANTABLE {
        let _ = writeln!(s, "\t{}: {},", role.as_str(), caps_list(caps));
    }
    s.push_str("};\n");
    s.push_str(
        "export const CAP_LABELS: Readonly<Record<Cap, { label: string; sub: string }>> = {\n",
    );
    for cap in CAPS {
        let (label, sub) = cap.label();
        s.push_str(&label_entry(cap.as_str(), [("label", label), ("sub", sub)]));
    }
    s.push_str("};\n");
    s.push_str(
        "export const TIER_LABELS: Readonly<Record<Tier, { label: string; long: string }>> = {\n",
    );
    for tier in TIERS {
        let (label, long) = tier.label();
        s.push_str(&label_entry(
            tier.as_str(),
            [("label", label), ("long", long)],
        ));
    }
    s.push_str("};\n");
    let _ = writeln!(
        s,
        "export type ArmClass = {};",
        ARM_CLASSES
            .iter()
            .map(|c: &ArmClass| format!("'{}'", c.as_str()))
            .collect::<Vec<_>>()
            .join(" | ")
    );
    s
}

/// `src/lib/access/rpc-requirements.gen.ts`, one line per arm, sorted.
pub fn render_rpc_requirements_ts() -> String {
    let mut rows: Vec<_> = RPC_REQUIREMENTS.iter().collect();
    rows.sort_by_key(|(name, _)| *name);
    let mut s = String::new();
    s.push_str(HEADER);
    s.push('\n');
    s.push_str("import type { ArmClass, Cap } from './caps.gen';\n\n");
    s.push_str("type ArmRequirement = { caps: readonly Cap[]; class: ArmClass };\n\n");
    s.push_str("export const RPC_REQUIREMENTS: Readonly<Record<string, ArmRequirement>> = {\n");
    for (name, req) in rows {
        let caps = quoted(req.caps.iter().map(|c| c.as_str()));
        let class = req.class.as_str();
        let one = format!("\t{name}: {{ caps: [{caps}], class: '{class}' }},");
        if width(&one) <= WIDTH {
            s.push_str(&one);
            s.push('\n');
        } else {
            let _ = writeln!(
                s,
                "\t{name}: {{\n\t\tcaps: [{caps}],\n\t\tclass: '{class}',\n\t}},"
            );
        }
    }
    s.push_str("};\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn generated(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("src/lib/access")
            .join(name)
    }

    /// A-2: the checked-in file equals the render. On a mismatch the message
    /// carries the whole expected file; `IKENGA_UPDATE_GENERATED=1` rewrites.
    fn golden(name: &str, expected: String) {
        let path = generated(name);
        if std::env::var_os("IKENGA_UPDATE_GENERATED").is_some_and(|v| v == "1") {
            std::fs::write(&path, &expected).unwrap();
            return;
        }
        let actual = std::fs::read_to_string(&path).unwrap_or_default();
        assert!(
            actual == expected,
            "{} is stale. Regenerate with `IKENGA_UPDATE_GENERATED=1 cargo test --lib \
             access::caps_ts`, or replace it with exactly:\n\
             ----- BEGIN {name} -----\n{expected}----- END {name} -----",
            path.display()
        );
    }

    #[test]
    fn caps_gen_ts_is_current() {
        golden("caps.gen.ts", render_caps_ts());
    }

    #[test]
    fn rpc_requirements_gen_ts_is_current() {
        golden("rpc-requirements.gen.ts", render_rpc_requirements_ts());
    }

    #[test]
    fn renders_are_deterministic_and_headed() {
        assert_eq!(render_caps_ts(), render_caps_ts());
        assert!(render_caps_ts().starts_with(HEADER));
        assert!(render_rpc_requirements_ts().starts_with(HEADER));
        assert!(render_caps_ts().contains("Chi\u{2019}s"));
    }
}
