//! The one generated-types source (G-ACCESS §1.5): pure renderers of
//! `src/lib/access/caps.gen.ts` (from `caps.rs`) and
//! `src/lib/access/rpc-requirements.gen.ts` (from `rpc_requirements.rs`),
//! plus a golden test per file (A-2).
//!
//! The output is already in Biome's format (tabs, single quotes, ES5
//! trailing commas, 100 columns), so `bun run fmt` leaves it alone.
//!
//! Regenerate with `IKENGA_UPDATE_GENERATED=1 cargo test --lib --no-default-features access::caps_ts`.
//! A failing golden test prints the full expected file, so a WP that can't
//! build locally copies CI's output into its PR.

use super::caps::{
    ArmClass, Cap, ACCESS_SCHEMA_VERSION, CAP_LABELS, NEVER_GRANTABLE, ROLE_DEFAULT_CAPS,
    TIER_CAPS, TIER_LABELS,
};
use super::caps::{CapSet, Role, Tier};
use super::rpc_requirements::RPC_REQUIREMENTS;

const HEADER: &str =
    "// GENERATED by src-tauri/src/access/caps_ts.rs — do not edit (G-ACCESS §1.5)\n";
const LINE_WIDTH: usize = 100;
/// Biome's `indentWidth` (a tab counts this many columns).
const TAB_WIDTH: usize = 2;

fn quote(s: &str) -> String {
    format!("'{}'", s.replace('\\', "\\\\").replace('\'', "\\'"))
}

fn width(indent: usize, text: &str) -> usize {
    indent * TAB_WIDTH + text.chars().count()
}

fn tabs(n: usize) -> String {
    "\t".repeat(n)
}

/// `[…]` on one line when `prefix[…]suffix` fits at `indent`, else one
/// element per line.
fn array(indent: usize, prefix: &str, items: &[String], suffix: &str) -> String {
    let one = format!("{prefix}[{}]{suffix}", items.join(", "));
    if items.is_empty() || width(indent, &one) <= LINE_WIDTH {
        return format!("{}{one}\n", tabs(indent));
    }
    let mut out = format!("{}{prefix}[\n", tabs(indent));
    for item in items {
        out.push_str(&format!("{}{item},\n", tabs(indent + 1)));
    }
    out.push_str(&format!("{}]{suffix}\n", tabs(indent)));
    out
}

fn caps_list(caps: &[Cap]) -> Vec<String> {
    caps.iter().map(|c| quote(c.as_str())).collect()
}

/// `src/lib/access/caps.gen.ts`.
pub fn render_caps_ts() -> String {
    let mut s = String::from(HEADER);
    s.push('\n');
    s.push_str(&format!(
        "export const ACCESS_SCHEMA_VERSION = {ACCESS_SCHEMA_VERSION} as const;\n\n"
    ));
    s.push_str(&array(
        0,
        "export const CAPS = ",
        &caps_list(&Cap::ALL),
        " as const;",
    ));
    s.push_str("export type Cap = (typeof CAPS)[number];\n\n");
    let tiers: Vec<String> = Tier::ALL.iter().map(|t| quote(t.as_str())).collect();
    s.push_str(&array(0, "export const TIERS = ", &tiers, " as const;"));
    s.push_str("export type Tier = (typeof TIERS)[number];\n\n");
    s.push_str("export const TIER_CAPS: Readonly<Record<Tier, readonly Cap[]>> = {\n");
    for (tier, caps) in TIER_CAPS {
        s.push_str(&array(
            1,
            &format!("{}: ", tier.as_str()),
            &caps_list(caps),
            ",",
        ));
    }
    s.push_str("};\n\n");
    let roles: Vec<String> = Role::ALL.iter().map(|r| quote(r.as_str())).collect();
    s.push_str(&array(0, "export const ROLES = ", &roles, " as const;"));
    s.push_str("export type Role = (typeof ROLES)[number];\n\n");
    s.push_str("export const ROLE_DEFAULT_CAPS: Readonly<Record<Role, readonly Cap[]>> = {\n");
    for (role, caps) in ROLE_DEFAULT_CAPS {
        s.push_str(&array(
            1,
            &format!("{}: ", role.as_str()),
            &caps_list(caps),
            ",",
        ));
    }
    s.push_str("};\n\n");
    s.push_str(
        "export const NEVER_GRANTABLE: Readonly<Record<Exclude<Role, 'owner'>, readonly Cap[]>> = {\n",
    );
    for (role, caps) in NEVER_GRANTABLE {
        s.push_str(&array(
            1,
            &format!("{}: ", role.as_str()),
            &caps_list(caps),
            ",",
        ));
    }
    s.push_str("};\n\n");
    s.push_str(
        "export const CAP_LABELS: Readonly<Record<Cap, { label: string; sub: string }>> = {\n",
    );
    for (cap, label, sub) in CAP_LABELS {
        s.push_str(&format!("\t{}: {{\n", cap.as_str()));
        s.push_str(&format!("\t\tlabel: {},\n", quote(label)));
        s.push_str(&format!("\t\tsub: {},\n", quote(sub)));
        s.push_str("\t},\n");
    }
    s.push_str("};\n\n");
    s.push_str(
        "export const TIER_LABELS: Readonly<Record<Tier, { label: string; long: string }>> = {\n",
    );
    for (tier, label, long) in TIER_LABELS {
        s.push_str(&format!("\t{}: {{\n", tier.as_str()));
        s.push_str(&format!("\t\tlabel: {},\n", quote(label)));
        s.push_str(&format!("\t\tlong: {},\n", quote(long)));
        s.push_str("\t},\n");
    }
    s.push_str("};\n\n");
    let classes: Vec<String> = ArmClass::ALL.iter().map(|c| quote(c.as_str())).collect();
    s.push_str(&format!(
        "export type ArmClass = {};\n",
        classes.join(" | ")
    ));
    s
}

fn caps_of(set: CapSet) -> Vec<String> {
    set.iter().map(|c| quote(c.as_str())).collect()
}

/// `src/lib/access/rpc-requirements.gen.ts`.
pub fn render_rpc_requirements_ts() -> String {
    let mut s = String::from(HEADER);
    s.push('\n');
    s.push_str("import type { ArmClass, Cap } from './caps.gen';\n\n");
    s.push_str("type Requirement = { caps: readonly Cap[]; class: ArmClass };\n\n");
    s.push_str("export const RPC_REQUIREMENTS: Readonly<Record<string, Requirement>> = {\n");
    for (name, req) in RPC_REQUIREMENTS {
        let caps = caps_of(req.caps);
        let class = quote(req.class.as_str());
        let one = format!("{name}: {{ caps: [{}], class: {class} }},", caps.join(", "));
        if width(1, &one) <= LINE_WIDTH {
            s.push_str(&format!("\t{one}\n"));
        } else {
            s.push_str(&format!("\t{name}: {{\n"));
            s.push_str(&array(2, "caps: ", &caps, ","));
            s.push_str(&format!("\t\tclass: {class},\n"));
            s.push_str("\t},\n");
        }
    }
    s.push_str("};\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn golden(rel: &str, expected: &str) {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join(rel);
        if std::env::var("IKENGA_UPDATE_GENERATED").as_deref() == Ok("1") {
            std::fs::write(&path, expected).unwrap();
            return;
        }
        let actual = std::fs::read_to_string(&path).unwrap_or_default();
        assert!(
            actual == expected,
            "{rel} is out of date with its Rust source (G-ACCESS §1.5). Regenerate with \
             `IKENGA_UPDATE_GENERATED=1 cargo test --lib --no-default-features access::caps_ts`, \
             or replace the file with exactly this:\n\
             ----- BEGIN {rel} -----\n{expected}----- END {rel} -----"
        );
    }

    /// A-2.
    #[test]
    fn caps_gen_ts_matches_caps_rs() {
        golden("src/lib/access/caps.gen.ts", &render_caps_ts());
    }

    /// A-2.
    #[test]
    fn rpc_requirements_gen_ts_matches_rpc_requirements_rs() {
        golden(
            "src/lib/access/rpc-requirements.gen.ts",
            &render_rpc_requirements_ts(),
        );
    }

    #[test]
    fn renderers_carry_the_header_and_every_row() {
        let caps = render_caps_ts();
        assert!(caps.starts_with(HEADER));
        for cap in Cap::ALL {
            assert!(caps.contains(&quote(cap.as_str())));
        }
        let reqs = render_rpc_requirements_ts();
        for (name, _) in RPC_REQUIREMENTS {
            assert!(reqs.contains(&format!("\t{name}: {{")), "{name}");
        }
    }
}
