// GENERATED by src-tauri/src/access/caps_ts.rs — do not edit (G-ACCESS §1.5)

export const ACCESS_SCHEMA_VERSION = 1 as const;
export const CAPS = [
	'files',
	'sessions',
	'dispatch',
	'approve',
	'install',
	'settings',
	'secrets',
] as const;
export type Cap = (typeof CAPS)[number];
export const TIERS = ['view', 'dispatch', 'approve', 'full'] as const;
export type Tier = (typeof TIERS)[number];
export const TIER_CAPS: Readonly<Record<Tier, readonly Cap[]>> = {
	view: ['files', 'sessions'],
	dispatch: ['files', 'sessions', 'dispatch'],
	approve: ['files', 'sessions', 'dispatch', 'approve'],
	full: ['files', 'sessions', 'dispatch', 'approve', 'install', 'settings', 'secrets'],
};
export const ROLES = ['owner', 'operator', 'reviewer', 'guest'] as const;
export type Role = (typeof ROLES)[number];
export const ROLE_DEFAULT_CAPS: Readonly<Record<Role, readonly Cap[]>> = {
	owner: ['files', 'sessions', 'dispatch', 'approve', 'install', 'settings', 'secrets'],
	operator: ['files', 'sessions', 'dispatch', 'approve'],
	reviewer: ['files', 'sessions'],
	guest: [],
};
export const NEVER_GRANTABLE: Readonly<Record<Exclude<Role, 'owner'>, readonly Cap[]>> = {
	operator: ['secrets'],
	reviewer: ['secrets'],
	guest: ['secrets'],
};
export const CAP_LABELS: Readonly<Record<Cap, { label: string; sub: string }>> = {
	files: { label: 'View files', sub: 'The project tree and file contents' },
	sessions: { label: 'View sessions', sub: 'Live and past Chi transcripts, cost, tool feed' },
	dispatch: { label: 'Dispatch to Chi', sub: 'Send an instruction to a session or start a run' },
	approve: { label: 'Approve permissions', sub: 'Answer Chi’s asks on your behalf' },
	install: { label: 'Install Ngwa', sub: 'Add or update packages in this project' },
	settings: { label: 'Edit settings', sub: 'Change project-scoped configuration' },
	secrets: { label: 'Read secrets', sub: 'Never grantable — the vault stays on the host' },
};
export const TIER_LABELS: Readonly<Record<Tier, { label: string; long: string }>> = {
	view: {
		label: 'View only',
		long: 'Read files, artifacts and session transcripts. Cannot type at Chi.',
	},
	dispatch: {
		label: 'View + dispatch',
		long: 'Everything above, plus sending instructions to a session.',
	},
	approve: {
		label: 'Dispatch + approve',
		long: 'Everything above, plus answering Chi’s permission asks.',
	},
	full: { label: 'Full', long: 'Everything this machine can do, including settings and packages.' },
};
export type ArmClass = 'shared' | 'owner' | 'operator' | 'access' | 'internal';
