import { render, screen, fireEvent, cleanup } from '@testing-library/react';
import { describe, expect, it, vi, afterEach } from 'vitest';
import {
	FrontmatterFormEditor,
	splitFrontmatter,
	parseFrontmatter,
	serializeFrontmatter,
	assembleDocument,
} from './frontmatter-form-editor';

describe('FrontmatterFormEditor — WP-25', () => {
	afterEach(() => {
		cleanup();
	});
	const sampleDoc = `---
name: release-notes
description: Generates concise release notes
allowed-tools: Read, Grep, Glob
model: claude-3-5-sonnet
---

# Release Notes Tool

<!-- ikenga:auto:start body -->
Content generated by Chi
<!-- ikenga:auto:end body -->

Manual notes at the bottom.
`;

	it('splits frontmatter and body accurately', () => {
		const { frontmatterRaw, bodyRaw, hasFrontmatter } = splitFrontmatter(sampleDoc);

		expect(hasFrontmatter).toBe(true);
		expect(frontmatterRaw).toContain('name: release-notes');
		expect(bodyRaw).toContain('# Release Notes Tool');
		expect(bodyRaw).toContain('<!-- ikenga:auto:start body -->');
	});

	it('parses structured fields from YAML string', () => {
		const { frontmatterRaw } = splitFrontmatter(sampleDoc);
		const data = parseFrontmatter(frontmatterRaw);

		expect(data.name).toBe('release-notes');
		expect(data.description).toBe('Generates concise release notes');
		expect(data.allowedTools).toEqual(['Read', 'Grep', 'Glob']);
		expect(data.model).toBe('claude-3-5-sonnet');
	});

	it('serializes structured frontmatter back to YAML', () => {
		const data = {
			name: 'my-agent',
			description: 'Test agent',
			allowedTools: ['Bash', 'Edit'],
			customFields: { version: '1.0.0' },
		};
		const yaml = serializeFrontmatter(data);

		expect(yaml).toContain('name: my-agent');
		expect(yaml).toContain('description: Test agent');
		expect(yaml).toContain('allowed-tools: Bash, Edit');
		expect(yaml).toContain('version: 1.0.0');

		const doc = assembleDocument(yaml, '# Body text');
		expect(doc).toContain('---\nname: my-agent');
		expect(doc).toContain('# Body text');
	});

	it('renders form inputs and edits frontmatter while preserving fenced body', () => {
		const handleChange = vi.fn();
		render(<FrontmatterFormEditor value={sampleDoc} onChange={handleChange} />);

		const nameInput = screen.getByTestId('field-name') as HTMLInputElement;
		expect(nameInput.value).toBe('release-notes');

		// Modify name
		fireEvent.change(nameInput, { target: { value: 'updated-notes' } });

		expect(handleChange).toHaveBeenCalled();
		const updatedDoc = handleChange.mock.calls[0][0];

		// New frontmatter name present
		expect(updatedDoc).toContain('name: updated-notes');

		// Fenced body and manual text completely preserved
		expect(updatedDoc).toContain('<!-- ikenga:auto:start body -->');
		expect(updatedDoc).toContain('Content generated by Chi');
		expect(updatedDoc).toContain('<!-- ikenga:auto:end body -->');
		expect(updatedDoc).toContain('Manual notes at the bottom.');
	});

	it('toggles between form mode and raw mode', () => {
		const handleChange = vi.fn();
		render(<FrontmatterFormEditor value={sampleDoc} onChange={handleChange} />);

		// Switch to raw mode
		const rawBtn = screen.getByTestId('mode-raw-btn');
		fireEvent.click(rawBtn);

		const rawTextarea = screen.getByTestId('raw-textarea') as HTMLTextAreaElement;
		expect(rawTextarea.value).toBe(sampleDoc);

		// Switch back to form mode
		const formBtn = screen.getByTestId('mode-form-btn');
		fireEvent.click(formBtn);

		expect(screen.getByTestId('field-name')).toBeDefined();
	});
});
