/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as ScratchpadsRouteImport } from './routes/scratchpads'
import { Route as PkgKernelStatusRouteImport } from './routes/pkg-kernel-status'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as InstallRouteImport } from './routes/install'
import { Route as CronRouteImport } from './routes/cron'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AgentRunsRouteImport } from './routes/agent-runs'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as OutboxRouteRouteImport } from './routes/outbox/route'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as ClaudeRouteRouteImport } from './routes/claude/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as NgwaIndexRouteImport } from './routes/ngwa/index'
import { Route as ChiIndexRouteImport } from './routes/chi/index'
import { Route as SettingsTerminalRouteImport } from './routes/settings/terminal'
import { Route as SettingsStorageRouteImport } from './routes/settings/storage'
import { Route as SettingsSecretsRouteImport } from './routes/settings/secrets'
import { Route as SettingsProjectsRouteImport } from './routes/settings/projects'
import { Route as SettingsPkgHealthRouteImport } from './routes/settings/pkg-health'
import { Route as SettingsPkgAuditRouteImport } from './routes/settings/pkg-audit'
import { Route as SettingsPackagesRouteImport } from './routes/settings/packages'
import { Route as SettingsOnboardingRouteImport } from './routes/settings/onboarding'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsDataHealthRouteImport } from './routes/settings/data-health'
import { Route as SettingsBackupRouteImport } from './routes/settings/backup'
import { Route as SettingsArtifactGridRouteImport } from './routes/settings/artifact-grid'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAgentRouteImport } from './routes/settings/agent'
import { Route as SettingsActivityBarRouteImport } from './routes/settings/activity-bar'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as ProjectsNewArtifactRouteImport } from './routes/projects/new-artifact'
import { Route as ProjectDashboardRouteImport } from './routes/project/dashboard'
import { Route as PackagesBrowseRouteImport } from './routes/packages_.browse'
import { Route as OutboxSocialRouteImport } from './routes/outbox/social'
import { Route as OutboxSentRouteImport } from './routes/outbox/sent'
import { Route as OutboxNewsletterRouteImport } from './routes/outbox/newsletter'
import { Route as OutboxEmailRouteImport } from './routes/outbox/email'
import { Route as OutboxApprovalsRouteImport } from './routes/outbox/approvals'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as OnboardingSummaryRouteImport } from './routes/onboarding/summary'
import { Route as OnboardingScaffoldingRouteImport } from './routes/onboarding/scaffolding'
import { Route as OnboardingRootsRouteImport } from './routes/onboarding/roots'
import { Route as OnboardingPackagesRouteImport } from './routes/onboarding/packages'
import { Route as OnboardingConnectorsRouteImport } from './routes/onboarding/connectors'
import { Route as OnboardingAppearanceRouteImport } from './routes/onboarding/appearance'
import { Route as OnboardingAgentRouteImport } from './routes/onboarding/agent'
import { Route as NgwaStoreRouteImport } from './routes/ngwa/store'
import { Route as NgwaInstalledRouteImport } from './routes/ngwa/installed'
import { Route as DevUiroutesSmokeRouteImport } from './routes/dev/uiroutes-smoke'
import { Route as DevSettingsSmokeRouteImport } from './routes/dev/settings-smoke'
import { Route as DevPkgSmokeRouteImport } from './routes/dev/pkg-smoke'
import { Route as DevPermsSmokeRouteImport } from './routes/dev/perms-smoke'
import { Route as DevMcpSmokeRouteImport } from './routes/dev/mcp-smoke'
import { Route as DevLspSmokeRouteImport } from './routes/dev/lsp-smoke'
import { Route as DevIykeSmokeRouteImport } from './routes/dev/iyke-smoke'
import { Route as DevIframeMountSmokeRouteImport } from './routes/dev/iframe-mount-smoke'
import { Route as DevCronSmokeRouteImport } from './routes/dev/cron-smoke'
import { Route as DevClaudeAssetsSmokeRouteImport } from './routes/dev/claude-assets-smoke'
import { Route as ArtifactsHomeRouteImport } from './routes/artifacts/home'
import { Route as PkgPkgIdRouteRouteImport } from './routes/pkg/$pkgId/route'
import { Route as PkgPkgIdIndexRouteImport } from './routes/pkg/$pkgId/index'
import { Route as PkgPkgIdSplatRouteImport } from './routes/pkg/$pkgId/$'
import { Route as ArtifactsByKindKindRouteImport } from './routes/artifacts/by-kind.$kind'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ScratchpadsRoute = ScratchpadsRouteImport.update({
  id: '/scratchpads',
  path: '/scratchpads',
  getParentRoute: () => rootRouteImport,
} as any)
const PkgKernelStatusRoute = PkgKernelStatusRouteImport.update({
  id: '/pkg-kernel-status',
  path: '/pkg-kernel-status',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRunsRoute = AgentRunsRouteImport.update({
  id: '/agent-runs',
  path: '/agent-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboxRouteRoute = OutboxRouteRouteImport.update({
  id: '/outbox',
  path: '/outbox',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeRouteRoute = ClaudeRouteRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const NgwaIndexRoute = NgwaIndexRouteImport.update({
  id: '/ngwa/',
  path: '/ngwa/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiIndexRoute = ChiIndexRouteImport.update({
  id: '/chi/',
  path: '/chi/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTerminalRoute = SettingsTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsSecretsRoute = SettingsSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProjectsRoute = SettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPkgHealthRoute = SettingsPkgHealthRouteImport.update({
  id: '/pkg-health',
  path: '/pkg-health',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPkgAuditRoute = SettingsPkgAuditRouteImport.update({
  id: '/pkg-audit',
  path: '/pkg-audit',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPackagesRoute = SettingsPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsOnboardingRoute = SettingsOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsDataHealthRoute = SettingsDataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsBackupRoute = SettingsBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsArtifactGridRoute = SettingsArtifactGridRouteImport.update({
  id: '/artifact-grid',
  path: '/artifact-grid',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAgentRoute = SettingsAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsActivityBarRoute = SettingsActivityBarRouteImport.update({
  id: '/activity-bar',
  path: '/activity-bar',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ProjectsNewArtifactRoute = ProjectsNewArtifactRouteImport.update({
  id: '/projects/new-artifact',
  path: '/projects/new-artifact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDashboardRoute = ProjectDashboardRouteImport.update({
  id: '/project/dashboard',
  path: '/project/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesBrowseRoute = PackagesBrowseRouteImport.update({
  id: '/packages_/browse',
  path: '/packages/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboxSocialRoute = OutboxSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => OutboxRouteRoute,
} as any)
const OutboxSentRoute = OutboxSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => OutboxRouteRoute,
} as any)
const OutboxNewsletterRoute = OutboxNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => OutboxRouteRoute,
} as any)
const OutboxEmailRoute = OutboxEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => OutboxRouteRoute,
} as any)
const OutboxApprovalsRoute = OutboxApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => OutboxRouteRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingSummaryRoute = OnboardingSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingScaffoldingRoute = OnboardingScaffoldingRouteImport.update({
  id: '/scaffolding',
  path: '/scaffolding',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingRootsRoute = OnboardingRootsRouteImport.update({
  id: '/roots',
  path: '/roots',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingPackagesRoute = OnboardingPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingConnectorsRoute = OnboardingConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingAppearanceRoute = OnboardingAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingAgentRoute = OnboardingAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const NgwaStoreRoute = NgwaStoreRouteImport.update({
  id: '/ngwa/store',
  path: '/ngwa/store',
  getParentRoute: () => rootRouteImport,
} as any)
const NgwaInstalledRoute = NgwaInstalledRouteImport.update({
  id: '/ngwa/installed',
  path: '/ngwa/installed',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiroutesSmokeRoute = DevUiroutesSmokeRouteImport.update({
  id: '/dev/uiroutes-smoke',
  path: '/dev/uiroutes-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSettingsSmokeRoute = DevSettingsSmokeRouteImport.update({
  id: '/dev/settings-smoke',
  path: '/dev/settings-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPkgSmokeRoute = DevPkgSmokeRouteImport.update({
  id: '/dev/pkg-smoke',
  path: '/dev/pkg-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPermsSmokeRoute = DevPermsSmokeRouteImport.update({
  id: '/dev/perms-smoke',
  path: '/dev/perms-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMcpSmokeRoute = DevMcpSmokeRouteImport.update({
  id: '/dev/mcp-smoke',
  path: '/dev/mcp-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLspSmokeRoute = DevLspSmokeRouteImport.update({
  id: '/dev/lsp-smoke',
  path: '/dev/lsp-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIykeSmokeRoute = DevIykeSmokeRouteImport.update({
  id: '/dev/iyke-smoke',
  path: '/dev/iyke-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIframeMountSmokeRoute = DevIframeMountSmokeRouteImport.update({
  id: '/dev/iframe-mount-smoke',
  path: '/dev/iframe-mount-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const DevCronSmokeRoute = DevCronSmokeRouteImport.update({
  id: '/dev/cron-smoke',
  path: '/dev/cron-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const DevClaudeAssetsSmokeRoute = DevClaudeAssetsSmokeRouteImport.update({
  id: '/dev/claude-assets-smoke',
  path: '/dev/claude-assets-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsHomeRoute = ArtifactsHomeRouteImport.update({
  id: '/artifacts/home',
  path: '/artifacts/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PkgPkgIdRouteRoute = PkgPkgIdRouteRouteImport.update({
  id: '/pkg/$pkgId',
  path: '/pkg/$pkgId',
  getParentRoute: () => rootRouteImport,
} as any)
const PkgPkgIdIndexRoute = PkgPkgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PkgPkgIdRouteRoute,
} as any)
const PkgPkgIdSplatRoute = PkgPkgIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PkgPkgIdRouteRoute,
} as any)
const ArtifactsByKindKindRoute = ArtifactsByKindKindRouteImport.update({
  id: '/artifacts/by-kind/$kind',
  path: '/artifacts/by-kind/$kind',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claude': typeof ClaudeRouteRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/outbox': typeof OutboxRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/agent-runs': typeof AgentRunsRoute
  '/automations': typeof AutomationsRoute
  '/cron': typeof CronRoute
  '/install': typeof InstallRoute
  '/packages': typeof PackagesRoute
  '/pkg-kernel-status': typeof PkgKernelStatusRoute
  '/scratchpads': typeof ScratchpadsRoute
  '/todos': typeof TodosRoute
  '/pkg/$pkgId': typeof PkgPkgIdRouteRouteWithChildren
  '/artifacts/home': typeof ArtifactsHomeRoute
  '/dev/claude-assets-smoke': typeof DevClaudeAssetsSmokeRoute
  '/dev/cron-smoke': typeof DevCronSmokeRoute
  '/dev/iframe-mount-smoke': typeof DevIframeMountSmokeRoute
  '/dev/iyke-smoke': typeof DevIykeSmokeRoute
  '/dev/lsp-smoke': typeof DevLspSmokeRoute
  '/dev/mcp-smoke': typeof DevMcpSmokeRoute
  '/dev/perms-smoke': typeof DevPermsSmokeRoute
  '/dev/pkg-smoke': typeof DevPkgSmokeRoute
  '/dev/settings-smoke': typeof DevSettingsSmokeRoute
  '/dev/uiroutes-smoke': typeof DevUiroutesSmokeRoute
  '/ngwa/installed': typeof NgwaInstalledRoute
  '/ngwa/store': typeof NgwaStoreRoute
  '/onboarding/agent': typeof OnboardingAgentRoute
  '/onboarding/appearance': typeof OnboardingAppearanceRoute
  '/onboarding/connectors': typeof OnboardingConnectorsRoute
  '/onboarding/packages': typeof OnboardingPackagesRoute
  '/onboarding/roots': typeof OnboardingRootsRoute
  '/onboarding/scaffolding': typeof OnboardingScaffoldingRoute
  '/onboarding/summary': typeof OnboardingSummaryRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/outbox/approvals': typeof OutboxApprovalsRoute
  '/outbox/email': typeof OutboxEmailRoute
  '/outbox/newsletter': typeof OutboxNewsletterRoute
  '/outbox/sent': typeof OutboxSentRoute
  '/outbox/social': typeof OutboxSocialRoute
  '/packages/browse': typeof PackagesBrowseRoute
  '/project/dashboard': typeof ProjectDashboardRoute
  '/projects/new-artifact': typeof ProjectsNewArtifactRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/activity-bar': typeof SettingsActivityBarRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/artifact-grid': typeof SettingsArtifactGridRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/data-health': typeof SettingsDataHealthRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/onboarding': typeof SettingsOnboardingRoute
  '/settings/packages': typeof SettingsPackagesRoute
  '/settings/pkg-audit': typeof SettingsPkgAuditRoute
  '/settings/pkg-health': typeof SettingsPkgHealthRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/secrets': typeof SettingsSecretsRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/terminal': typeof SettingsTerminalRoute
  '/chi/': typeof ChiIndexRoute
  '/ngwa/': typeof NgwaIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/artifacts/by-kind/$kind': typeof ArtifactsByKindKindRoute
  '/pkg/$pkgId/$': typeof PkgPkgIdSplatRoute
  '/pkg/$pkgId/': typeof PkgPkgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claude': typeof ClaudeRouteRoute
  '/outbox': typeof OutboxRouteRouteWithChildren
  '/agent-runs': typeof AgentRunsRoute
  '/automations': typeof AutomationsRoute
  '/cron': typeof CronRoute
  '/install': typeof InstallRoute
  '/packages': typeof PackagesRoute
  '/pkg-kernel-status': typeof PkgKernelStatusRoute
  '/scratchpads': typeof ScratchpadsRoute
  '/todos': typeof TodosRoute
  '/artifacts/home': typeof ArtifactsHomeRoute
  '/dev/claude-assets-smoke': typeof DevClaudeAssetsSmokeRoute
  '/dev/cron-smoke': typeof DevCronSmokeRoute
  '/dev/iframe-mount-smoke': typeof DevIframeMountSmokeRoute
  '/dev/iyke-smoke': typeof DevIykeSmokeRoute
  '/dev/lsp-smoke': typeof DevLspSmokeRoute
  '/dev/mcp-smoke': typeof DevMcpSmokeRoute
  '/dev/perms-smoke': typeof DevPermsSmokeRoute
  '/dev/pkg-smoke': typeof DevPkgSmokeRoute
  '/dev/settings-smoke': typeof DevSettingsSmokeRoute
  '/dev/uiroutes-smoke': typeof DevUiroutesSmokeRoute
  '/ngwa/installed': typeof NgwaInstalledRoute
  '/ngwa/store': typeof NgwaStoreRoute
  '/onboarding/agent': typeof OnboardingAgentRoute
  '/onboarding/appearance': typeof OnboardingAppearanceRoute
  '/onboarding/connectors': typeof OnboardingConnectorsRoute
  '/onboarding/packages': typeof OnboardingPackagesRoute
  '/onboarding/roots': typeof OnboardingRootsRoute
  '/onboarding/scaffolding': typeof OnboardingScaffoldingRoute
  '/onboarding/summary': typeof OnboardingSummaryRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/outbox/approvals': typeof OutboxApprovalsRoute
  '/outbox/email': typeof OutboxEmailRoute
  '/outbox/newsletter': typeof OutboxNewsletterRoute
  '/outbox/sent': typeof OutboxSentRoute
  '/outbox/social': typeof OutboxSocialRoute
  '/packages/browse': typeof PackagesBrowseRoute
  '/project/dashboard': typeof ProjectDashboardRoute
  '/projects/new-artifact': typeof ProjectsNewArtifactRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/activity-bar': typeof SettingsActivityBarRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/artifact-grid': typeof SettingsArtifactGridRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/data-health': typeof SettingsDataHealthRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/onboarding': typeof SettingsOnboardingRoute
  '/settings/packages': typeof SettingsPackagesRoute
  '/settings/pkg-audit': typeof SettingsPkgAuditRoute
  '/settings/pkg-health': typeof SettingsPkgHealthRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/secrets': typeof SettingsSecretsRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/terminal': typeof SettingsTerminalRoute
  '/chi': typeof ChiIndexRoute
  '/ngwa': typeof NgwaIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/project': typeof ProjectIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/artifacts/by-kind/$kind': typeof ArtifactsByKindKindRoute
  '/pkg/$pkgId/$': typeof PkgPkgIdSplatRoute
  '/pkg/$pkgId': typeof PkgPkgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claude': typeof ClaudeRouteRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/outbox': typeof OutboxRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/agent-runs': typeof AgentRunsRoute
  '/automations': typeof AutomationsRoute
  '/cron': typeof CronRoute
  '/install': typeof InstallRoute
  '/packages': typeof PackagesRoute
  '/pkg-kernel-status': typeof PkgKernelStatusRoute
  '/scratchpads': typeof ScratchpadsRoute
  '/todos': typeof TodosRoute
  '/pkg/$pkgId': typeof PkgPkgIdRouteRouteWithChildren
  '/artifacts/home': typeof ArtifactsHomeRoute
  '/dev/claude-assets-smoke': typeof DevClaudeAssetsSmokeRoute
  '/dev/cron-smoke': typeof DevCronSmokeRoute
  '/dev/iframe-mount-smoke': typeof DevIframeMountSmokeRoute
  '/dev/iyke-smoke': typeof DevIykeSmokeRoute
  '/dev/lsp-smoke': typeof DevLspSmokeRoute
  '/dev/mcp-smoke': typeof DevMcpSmokeRoute
  '/dev/perms-smoke': typeof DevPermsSmokeRoute
  '/dev/pkg-smoke': typeof DevPkgSmokeRoute
  '/dev/settings-smoke': typeof DevSettingsSmokeRoute
  '/dev/uiroutes-smoke': typeof DevUiroutesSmokeRoute
  '/ngwa/installed': typeof NgwaInstalledRoute
  '/ngwa/store': typeof NgwaStoreRoute
  '/onboarding/agent': typeof OnboardingAgentRoute
  '/onboarding/appearance': typeof OnboardingAppearanceRoute
  '/onboarding/connectors': typeof OnboardingConnectorsRoute
  '/onboarding/packages': typeof OnboardingPackagesRoute
  '/onboarding/roots': typeof OnboardingRootsRoute
  '/onboarding/scaffolding': typeof OnboardingScaffoldingRoute
  '/onboarding/summary': typeof OnboardingSummaryRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/outbox/approvals': typeof OutboxApprovalsRoute
  '/outbox/email': typeof OutboxEmailRoute
  '/outbox/newsletter': typeof OutboxNewsletterRoute
  '/outbox/sent': typeof OutboxSentRoute
  '/outbox/social': typeof OutboxSocialRoute
  '/packages_/browse': typeof PackagesBrowseRoute
  '/project/dashboard': typeof ProjectDashboardRoute
  '/projects/new-artifact': typeof ProjectsNewArtifactRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/activity-bar': typeof SettingsActivityBarRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/artifact-grid': typeof SettingsArtifactGridRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/data-health': typeof SettingsDataHealthRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/onboarding': typeof SettingsOnboardingRoute
  '/settings/packages': typeof SettingsPackagesRoute
  '/settings/pkg-audit': typeof SettingsPkgAuditRoute
  '/settings/pkg-health': typeof SettingsPkgHealthRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/secrets': typeof SettingsSecretsRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/terminal': typeof SettingsTerminalRoute
  '/chi/': typeof ChiIndexRoute
  '/ngwa/': typeof NgwaIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/artifacts/by-kind/$kind': typeof ArtifactsByKindKindRoute
  '/pkg/$pkgId/$': typeof PkgPkgIdSplatRoute
  '/pkg/$pkgId/': typeof PkgPkgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claude'
    | '/onboarding'
    | '/outbox'
    | '/settings'
    | '/agent-runs'
    | '/automations'
    | '/cron'
    | '/install'
    | '/packages'
    | '/pkg-kernel-status'
    | '/scratchpads'
    | '/todos'
    | '/pkg/$pkgId'
    | '/artifacts/home'
    | '/dev/claude-assets-smoke'
    | '/dev/cron-smoke'
    | '/dev/iframe-mount-smoke'
    | '/dev/iyke-smoke'
    | '/dev/lsp-smoke'
    | '/dev/mcp-smoke'
    | '/dev/perms-smoke'
    | '/dev/pkg-smoke'
    | '/dev/settings-smoke'
    | '/dev/uiroutes-smoke'
    | '/ngwa/installed'
    | '/ngwa/store'
    | '/onboarding/agent'
    | '/onboarding/appearance'
    | '/onboarding/connectors'
    | '/onboarding/packages'
    | '/onboarding/roots'
    | '/onboarding/scaffolding'
    | '/onboarding/summary'
    | '/onboarding/welcome'
    | '/outbox/approvals'
    | '/outbox/email'
    | '/outbox/newsletter'
    | '/outbox/sent'
    | '/outbox/social'
    | '/packages/browse'
    | '/project/dashboard'
    | '/projects/new-artifact'
    | '/settings/about'
    | '/settings/activity-bar'
    | '/settings/agent'
    | '/settings/appearance'
    | '/settings/artifact-grid'
    | '/settings/backup'
    | '/settings/data-health'
    | '/settings/integrations'
    | '/settings/onboarding'
    | '/settings/packages'
    | '/settings/pkg-audit'
    | '/settings/pkg-health'
    | '/settings/projects'
    | '/settings/secrets'
    | '/settings/storage'
    | '/settings/terminal'
    | '/chi/'
    | '/ngwa/'
    | '/onboarding/'
    | '/project/'
    | '/settings/'
    | '/artifacts/by-kind/$kind'
    | '/pkg/$pkgId/$'
    | '/pkg/$pkgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claude'
    | '/outbox'
    | '/agent-runs'
    | '/automations'
    | '/cron'
    | '/install'
    | '/packages'
    | '/pkg-kernel-status'
    | '/scratchpads'
    | '/todos'
    | '/artifacts/home'
    | '/dev/claude-assets-smoke'
    | '/dev/cron-smoke'
    | '/dev/iframe-mount-smoke'
    | '/dev/iyke-smoke'
    | '/dev/lsp-smoke'
    | '/dev/mcp-smoke'
    | '/dev/perms-smoke'
    | '/dev/pkg-smoke'
    | '/dev/settings-smoke'
    | '/dev/uiroutes-smoke'
    | '/ngwa/installed'
    | '/ngwa/store'
    | '/onboarding/agent'
    | '/onboarding/appearance'
    | '/onboarding/connectors'
    | '/onboarding/packages'
    | '/onboarding/roots'
    | '/onboarding/scaffolding'
    | '/onboarding/summary'
    | '/onboarding/welcome'
    | '/outbox/approvals'
    | '/outbox/email'
    | '/outbox/newsletter'
    | '/outbox/sent'
    | '/outbox/social'
    | '/packages/browse'
    | '/project/dashboard'
    | '/projects/new-artifact'
    | '/settings/about'
    | '/settings/activity-bar'
    | '/settings/agent'
    | '/settings/appearance'
    | '/settings/artifact-grid'
    | '/settings/backup'
    | '/settings/data-health'
    | '/settings/integrations'
    | '/settings/onboarding'
    | '/settings/packages'
    | '/settings/pkg-audit'
    | '/settings/pkg-health'
    | '/settings/projects'
    | '/settings/secrets'
    | '/settings/storage'
    | '/settings/terminal'
    | '/chi'
    | '/ngwa'
    | '/onboarding'
    | '/project'
    | '/settings'
    | '/artifacts/by-kind/$kind'
    | '/pkg/$pkgId/$'
    | '/pkg/$pkgId'
  id:
    | '__root__'
    | '/'
    | '/claude'
    | '/onboarding'
    | '/outbox'
    | '/settings'
    | '/agent-runs'
    | '/automations'
    | '/cron'
    | '/install'
    | '/packages'
    | '/pkg-kernel-status'
    | '/scratchpads'
    | '/todos'
    | '/pkg/$pkgId'
    | '/artifacts/home'
    | '/dev/claude-assets-smoke'
    | '/dev/cron-smoke'
    | '/dev/iframe-mount-smoke'
    | '/dev/iyke-smoke'
    | '/dev/lsp-smoke'
    | '/dev/mcp-smoke'
    | '/dev/perms-smoke'
    | '/dev/pkg-smoke'
    | '/dev/settings-smoke'
    | '/dev/uiroutes-smoke'
    | '/ngwa/installed'
    | '/ngwa/store'
    | '/onboarding/agent'
    | '/onboarding/appearance'
    | '/onboarding/connectors'
    | '/onboarding/packages'
    | '/onboarding/roots'
    | '/onboarding/scaffolding'
    | '/onboarding/summary'
    | '/onboarding/welcome'
    | '/outbox/approvals'
    | '/outbox/email'
    | '/outbox/newsletter'
    | '/outbox/sent'
    | '/outbox/social'
    | '/packages_/browse'
    | '/project/dashboard'
    | '/projects/new-artifact'
    | '/settings/about'
    | '/settings/activity-bar'
    | '/settings/agent'
    | '/settings/appearance'
    | '/settings/artifact-grid'
    | '/settings/backup'
    | '/settings/data-health'
    | '/settings/integrations'
    | '/settings/onboarding'
    | '/settings/packages'
    | '/settings/pkg-audit'
    | '/settings/pkg-health'
    | '/settings/projects'
    | '/settings/secrets'
    | '/settings/storage'
    | '/settings/terminal'
    | '/chi/'
    | '/ngwa/'
    | '/onboarding/'
    | '/project/'
    | '/settings/'
    | '/artifacts/by-kind/$kind'
    | '/pkg/$pkgId/$'
    | '/pkg/$pkgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaudeRouteRoute: typeof ClaudeRouteRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  OutboxRouteRoute: typeof OutboxRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AgentRunsRoute: typeof AgentRunsRoute
  AutomationsRoute: typeof AutomationsRoute
  CronRoute: typeof CronRoute
  InstallRoute: typeof InstallRoute
  PackagesRoute: typeof PackagesRoute
  PkgKernelStatusRoute: typeof PkgKernelStatusRoute
  ScratchpadsRoute: typeof ScratchpadsRoute
  TodosRoute: typeof TodosRoute
  PkgPkgIdRouteRoute: typeof PkgPkgIdRouteRouteWithChildren
  ArtifactsHomeRoute: typeof ArtifactsHomeRoute
  DevClaudeAssetsSmokeRoute: typeof DevClaudeAssetsSmokeRoute
  DevCronSmokeRoute: typeof DevCronSmokeRoute
  DevIframeMountSmokeRoute: typeof DevIframeMountSmokeRoute
  DevIykeSmokeRoute: typeof DevIykeSmokeRoute
  DevLspSmokeRoute: typeof DevLspSmokeRoute
  DevMcpSmokeRoute: typeof DevMcpSmokeRoute
  DevPermsSmokeRoute: typeof DevPermsSmokeRoute
  DevPkgSmokeRoute: typeof DevPkgSmokeRoute
  DevSettingsSmokeRoute: typeof DevSettingsSmokeRoute
  DevUiroutesSmokeRoute: typeof DevUiroutesSmokeRoute
  NgwaInstalledRoute: typeof NgwaInstalledRoute
  NgwaStoreRoute: typeof NgwaStoreRoute
  PackagesBrowseRoute: typeof PackagesBrowseRoute
  ProjectDashboardRoute: typeof ProjectDashboardRoute
  ProjectsNewArtifactRoute: typeof ProjectsNewArtifactRoute
  ChiIndexRoute: typeof ChiIndexRoute
  NgwaIndexRoute: typeof NgwaIndexRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
  ArtifactsByKindKindRoute: typeof ArtifactsByKindKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scratchpads': {
      id: '/scratchpads'
      path: '/scratchpads'
      fullPath: '/scratchpads'
      preLoaderRoute: typeof ScratchpadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pkg-kernel-status': {
      id: '/pkg-kernel-status'
      path: '/pkg-kernel-status'
      fullPath: '/pkg-kernel-status'
      preLoaderRoute: typeof PkgKernelStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-runs': {
      id: '/agent-runs'
      path: '/agent-runs'
      fullPath: '/agent-runs'
      preLoaderRoute: typeof AgentRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbox': {
      id: '/outbox'
      path: '/outbox'
      fullPath: '/outbox'
      preLoaderRoute: typeof OutboxRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude': {
      id: '/claude'
      path: '/claude'
      fullPath: '/claude'
      preLoaderRoute: typeof ClaudeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/ngwa/': {
      id: '/ngwa/'
      path: '/ngwa'
      fullPath: '/ngwa/'
      preLoaderRoute: typeof NgwaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi/': {
      id: '/chi/'
      path: '/chi'
      fullPath: '/chi/'
      preLoaderRoute: typeof ChiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/terminal': {
      id: '/settings/terminal'
      path: '/terminal'
      fullPath: '/settings/terminal'
      preLoaderRoute: typeof SettingsTerminalRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/secrets': {
      id: '/settings/secrets'
      path: '/secrets'
      fullPath: '/settings/secrets'
      preLoaderRoute: typeof SettingsSecretsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/projects': {
      id: '/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof SettingsProjectsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/pkg-health': {
      id: '/settings/pkg-health'
      path: '/pkg-health'
      fullPath: '/settings/pkg-health'
      preLoaderRoute: typeof SettingsPkgHealthRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/pkg-audit': {
      id: '/settings/pkg-audit'
      path: '/pkg-audit'
      fullPath: '/settings/pkg-audit'
      preLoaderRoute: typeof SettingsPkgAuditRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/packages': {
      id: '/settings/packages'
      path: '/packages'
      fullPath: '/settings/packages'
      preLoaderRoute: typeof SettingsPackagesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/onboarding': {
      id: '/settings/onboarding'
      path: '/onboarding'
      fullPath: '/settings/onboarding'
      preLoaderRoute: typeof SettingsOnboardingRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/data-health': {
      id: '/settings/data-health'
      path: '/data-health'
      fullPath: '/settings/data-health'
      preLoaderRoute: typeof SettingsDataHealthRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/backup': {
      id: '/settings/backup'
      path: '/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof SettingsBackupRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/artifact-grid': {
      id: '/settings/artifact-grid'
      path: '/artifact-grid'
      fullPath: '/settings/artifact-grid'
      preLoaderRoute: typeof SettingsArtifactGridRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/agent': {
      id: '/settings/agent'
      path: '/agent'
      fullPath: '/settings/agent'
      preLoaderRoute: typeof SettingsAgentRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/activity-bar': {
      id: '/settings/activity-bar'
      path: '/activity-bar'
      fullPath: '/settings/activity-bar'
      preLoaderRoute: typeof SettingsActivityBarRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/projects/new-artifact': {
      id: '/projects/new-artifact'
      path: '/projects/new-artifact'
      fullPath: '/projects/new-artifact'
      preLoaderRoute: typeof ProjectsNewArtifactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/dashboard': {
      id: '/project/dashboard'
      path: '/project/dashboard'
      fullPath: '/project/dashboard'
      preLoaderRoute: typeof ProjectDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages_/browse': {
      id: '/packages_/browse'
      path: '/packages/browse'
      fullPath: '/packages/browse'
      preLoaderRoute: typeof PackagesBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbox/social': {
      id: '/outbox/social'
      path: '/social'
      fullPath: '/outbox/social'
      preLoaderRoute: typeof OutboxSocialRouteImport
      parentRoute: typeof OutboxRouteRoute
    }
    '/outbox/sent': {
      id: '/outbox/sent'
      path: '/sent'
      fullPath: '/outbox/sent'
      preLoaderRoute: typeof OutboxSentRouteImport
      parentRoute: typeof OutboxRouteRoute
    }
    '/outbox/newsletter': {
      id: '/outbox/newsletter'
      path: '/newsletter'
      fullPath: '/outbox/newsletter'
      preLoaderRoute: typeof OutboxNewsletterRouteImport
      parentRoute: typeof OutboxRouteRoute
    }
    '/outbox/email': {
      id: '/outbox/email'
      path: '/email'
      fullPath: '/outbox/email'
      preLoaderRoute: typeof OutboxEmailRouteImport
      parentRoute: typeof OutboxRouteRoute
    }
    '/outbox/approvals': {
      id: '/outbox/approvals'
      path: '/approvals'
      fullPath: '/outbox/approvals'
      preLoaderRoute: typeof OutboxApprovalsRouteImport
      parentRoute: typeof OutboxRouteRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/summary': {
      id: '/onboarding/summary'
      path: '/summary'
      fullPath: '/onboarding/summary'
      preLoaderRoute: typeof OnboardingSummaryRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/scaffolding': {
      id: '/onboarding/scaffolding'
      path: '/scaffolding'
      fullPath: '/onboarding/scaffolding'
      preLoaderRoute: typeof OnboardingScaffoldingRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/roots': {
      id: '/onboarding/roots'
      path: '/roots'
      fullPath: '/onboarding/roots'
      preLoaderRoute: typeof OnboardingRootsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/packages': {
      id: '/onboarding/packages'
      path: '/packages'
      fullPath: '/onboarding/packages'
      preLoaderRoute: typeof OnboardingPackagesRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/connectors': {
      id: '/onboarding/connectors'
      path: '/connectors'
      fullPath: '/onboarding/connectors'
      preLoaderRoute: typeof OnboardingConnectorsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/appearance': {
      id: '/onboarding/appearance'
      path: '/appearance'
      fullPath: '/onboarding/appearance'
      preLoaderRoute: typeof OnboardingAppearanceRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/agent': {
      id: '/onboarding/agent'
      path: '/agent'
      fullPath: '/onboarding/agent'
      preLoaderRoute: typeof OnboardingAgentRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/ngwa/store': {
      id: '/ngwa/store'
      path: '/ngwa/store'
      fullPath: '/ngwa/store'
      preLoaderRoute: typeof NgwaStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngwa/installed': {
      id: '/ngwa/installed'
      path: '/ngwa/installed'
      fullPath: '/ngwa/installed'
      preLoaderRoute: typeof NgwaInstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/uiroutes-smoke': {
      id: '/dev/uiroutes-smoke'
      path: '/dev/uiroutes-smoke'
      fullPath: '/dev/uiroutes-smoke'
      preLoaderRoute: typeof DevUiroutesSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/settings-smoke': {
      id: '/dev/settings-smoke'
      path: '/dev/settings-smoke'
      fullPath: '/dev/settings-smoke'
      preLoaderRoute: typeof DevSettingsSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/pkg-smoke': {
      id: '/dev/pkg-smoke'
      path: '/dev/pkg-smoke'
      fullPath: '/dev/pkg-smoke'
      preLoaderRoute: typeof DevPkgSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/perms-smoke': {
      id: '/dev/perms-smoke'
      path: '/dev/perms-smoke'
      fullPath: '/dev/perms-smoke'
      preLoaderRoute: typeof DevPermsSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/mcp-smoke': {
      id: '/dev/mcp-smoke'
      path: '/dev/mcp-smoke'
      fullPath: '/dev/mcp-smoke'
      preLoaderRoute: typeof DevMcpSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/lsp-smoke': {
      id: '/dev/lsp-smoke'
      path: '/dev/lsp-smoke'
      fullPath: '/dev/lsp-smoke'
      preLoaderRoute: typeof DevLspSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/iyke-smoke': {
      id: '/dev/iyke-smoke'
      path: '/dev/iyke-smoke'
      fullPath: '/dev/iyke-smoke'
      preLoaderRoute: typeof DevIykeSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/iframe-mount-smoke': {
      id: '/dev/iframe-mount-smoke'
      path: '/dev/iframe-mount-smoke'
      fullPath: '/dev/iframe-mount-smoke'
      preLoaderRoute: typeof DevIframeMountSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/cron-smoke': {
      id: '/dev/cron-smoke'
      path: '/dev/cron-smoke'
      fullPath: '/dev/cron-smoke'
      preLoaderRoute: typeof DevCronSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/claude-assets-smoke': {
      id: '/dev/claude-assets-smoke'
      path: '/dev/claude-assets-smoke'
      fullPath: '/dev/claude-assets-smoke'
      preLoaderRoute: typeof DevClaudeAssetsSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/home': {
      id: '/artifacts/home'
      path: '/artifacts/home'
      fullPath: '/artifacts/home'
      preLoaderRoute: typeof ArtifactsHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pkg/$pkgId': {
      id: '/pkg/$pkgId'
      path: '/pkg/$pkgId'
      fullPath: '/pkg/$pkgId'
      preLoaderRoute: typeof PkgPkgIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pkg/$pkgId/': {
      id: '/pkg/$pkgId/'
      path: '/'
      fullPath: '/pkg/$pkgId/'
      preLoaderRoute: typeof PkgPkgIdIndexRouteImport
      parentRoute: typeof PkgPkgIdRouteRoute
    }
    '/pkg/$pkgId/$': {
      id: '/pkg/$pkgId/$'
      path: '/$'
      fullPath: '/pkg/$pkgId/$'
      preLoaderRoute: typeof PkgPkgIdSplatRouteImport
      parentRoute: typeof PkgPkgIdRouteRoute
    }
    '/artifacts/by-kind/$kind': {
      id: '/artifacts/by-kind/$kind'
      path: '/artifacts/by-kind/$kind'
      fullPath: '/artifacts/by-kind/$kind'
      preLoaderRoute: typeof ArtifactsByKindKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingRouteRouteChildren {
  OnboardingAgentRoute: typeof OnboardingAgentRoute
  OnboardingAppearanceRoute: typeof OnboardingAppearanceRoute
  OnboardingConnectorsRoute: typeof OnboardingConnectorsRoute
  OnboardingPackagesRoute: typeof OnboardingPackagesRoute
  OnboardingRootsRoute: typeof OnboardingRootsRoute
  OnboardingScaffoldingRoute: typeof OnboardingScaffoldingRoute
  OnboardingSummaryRoute: typeof OnboardingSummaryRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingAgentRoute: OnboardingAgentRoute,
  OnboardingAppearanceRoute: OnboardingAppearanceRoute,
  OnboardingConnectorsRoute: OnboardingConnectorsRoute,
  OnboardingPackagesRoute: OnboardingPackagesRoute,
  OnboardingRootsRoute: OnboardingRootsRoute,
  OnboardingScaffoldingRoute: OnboardingScaffoldingRoute,
  OnboardingSummaryRoute: OnboardingSummaryRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface OutboxRouteRouteChildren {
  OutboxApprovalsRoute: typeof OutboxApprovalsRoute
  OutboxEmailRoute: typeof OutboxEmailRoute
  OutboxNewsletterRoute: typeof OutboxNewsletterRoute
  OutboxSentRoute: typeof OutboxSentRoute
  OutboxSocialRoute: typeof OutboxSocialRoute
}

const OutboxRouteRouteChildren: OutboxRouteRouteChildren = {
  OutboxApprovalsRoute: OutboxApprovalsRoute,
  OutboxEmailRoute: OutboxEmailRoute,
  OutboxNewsletterRoute: OutboxNewsletterRoute,
  OutboxSentRoute: OutboxSentRoute,
  OutboxSocialRoute: OutboxSocialRoute,
}

const OutboxRouteRouteWithChildren = OutboxRouteRoute._addFileChildren(
  OutboxRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsActivityBarRoute: typeof SettingsActivityBarRoute
  SettingsAgentRoute: typeof SettingsAgentRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArtifactGridRoute: typeof SettingsArtifactGridRoute
  SettingsBackupRoute: typeof SettingsBackupRoute
  SettingsDataHealthRoute: typeof SettingsDataHealthRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsOnboardingRoute: typeof SettingsOnboardingRoute
  SettingsPackagesRoute: typeof SettingsPackagesRoute
  SettingsPkgAuditRoute: typeof SettingsPkgAuditRoute
  SettingsPkgHealthRoute: typeof SettingsPkgHealthRoute
  SettingsProjectsRoute: typeof SettingsProjectsRoute
  SettingsSecretsRoute: typeof SettingsSecretsRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsTerminalRoute: typeof SettingsTerminalRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsActivityBarRoute: SettingsActivityBarRoute,
  SettingsAgentRoute: SettingsAgentRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArtifactGridRoute: SettingsArtifactGridRoute,
  SettingsBackupRoute: SettingsBackupRoute,
  SettingsDataHealthRoute: SettingsDataHealthRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsOnboardingRoute: SettingsOnboardingRoute,
  SettingsPackagesRoute: SettingsPackagesRoute,
  SettingsPkgAuditRoute: SettingsPkgAuditRoute,
  SettingsPkgHealthRoute: SettingsPkgHealthRoute,
  SettingsProjectsRoute: SettingsProjectsRoute,
  SettingsSecretsRoute: SettingsSecretsRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsTerminalRoute: SettingsTerminalRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface PkgPkgIdRouteRouteChildren {
  PkgPkgIdSplatRoute: typeof PkgPkgIdSplatRoute
  PkgPkgIdIndexRoute: typeof PkgPkgIdIndexRoute
}

const PkgPkgIdRouteRouteChildren: PkgPkgIdRouteRouteChildren = {
  PkgPkgIdSplatRoute: PkgPkgIdSplatRoute,
  PkgPkgIdIndexRoute: PkgPkgIdIndexRoute,
}

const PkgPkgIdRouteRouteWithChildren = PkgPkgIdRouteRoute._addFileChildren(
  PkgPkgIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaudeRouteRoute: ClaudeRouteRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  OutboxRouteRoute: OutboxRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AgentRunsRoute: AgentRunsRoute,
  AutomationsRoute: AutomationsRoute,
  CronRoute: CronRoute,
  InstallRoute: InstallRoute,
  PackagesRoute: PackagesRoute,
  PkgKernelStatusRoute: PkgKernelStatusRoute,
  ScratchpadsRoute: ScratchpadsRoute,
  TodosRoute: TodosRoute,
  PkgPkgIdRouteRoute: PkgPkgIdRouteRouteWithChildren,
  ArtifactsHomeRoute: ArtifactsHomeRoute,
  DevClaudeAssetsSmokeRoute: DevClaudeAssetsSmokeRoute,
  DevCronSmokeRoute: DevCronSmokeRoute,
  DevIframeMountSmokeRoute: DevIframeMountSmokeRoute,
  DevIykeSmokeRoute: DevIykeSmokeRoute,
  DevLspSmokeRoute: DevLspSmokeRoute,
  DevMcpSmokeRoute: DevMcpSmokeRoute,
  DevPermsSmokeRoute: DevPermsSmokeRoute,
  DevPkgSmokeRoute: DevPkgSmokeRoute,
  DevSettingsSmokeRoute: DevSettingsSmokeRoute,
  DevUiroutesSmokeRoute: DevUiroutesSmokeRoute,
  NgwaInstalledRoute: NgwaInstalledRoute,
  NgwaStoreRoute: NgwaStoreRoute,
  PackagesBrowseRoute: PackagesBrowseRoute,
  ProjectDashboardRoute: ProjectDashboardRoute,
  ProjectsNewArtifactRoute: ProjectsNewArtifactRoute,
  ChiIndexRoute: ChiIndexRoute,
  NgwaIndexRoute: NgwaIndexRoute,
  ProjectIndexRoute: ProjectIndexRoute,
  ArtifactsByKindKindRoute: ArtifactsByKindKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
